val daggerVersion by extra { "2.47" }
val androidxCoreVersion by extra { "1.7.0" }
val junitVersion by extra { "4.13.2" }
val composeUiVersion by extra { "1.1.1" }
val navigationVersion by extra { "2.5.0" }
val androidCoreKtxVersion by extra { "1.7.0" }
val lifecycleVersion by extra { "2.5.0" }
val activityComposeVersion by extra { "1.3.1" }
val materialVersion by extra { "1.0.0" }
val protobufVersion by extra { "3.22.2" }
val roomVersion by extra { "2.5.2" }
val dataStoreVersion by extra { "1.0.0" }
val retrofitVersion by extra { "2.9.0" }
val okhttpLoggingInterceptorVersion by extra { "4.11.0" }
val coroutinesVersion by extra { "1.6.0" }
val kotlinVersion by extra { "1.6.10" }
val androidPluginVersion by extra { "7.3.1" }
val compileSdkVersion by extra { 33 }
val targetSdkVersion by extra { 33 }
val minSdkVersion by extra { 26 }
val appPackage by extra { "com.example.test" }

