# This is a basic workflow to help you get started with Actions

name: Assemble

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Assemble TestApp
        run: ./gradlew assemble
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: get-apk
          path: |
            app/build/outputs/apk/debug
